CREATE DATABASE Bino;
USE Bino;

DROP TABLE IF EXISTS Feedbacks;

CREATE TABLE Feedbacks
( 
  Id INT AUTO_INCREMENT NOT NULL,
  Name VARCHAR(256) NOT NULL,
  Email VARCHAR(256) NOT NULL,
  Subject VARCHAR(256) NOT NULL,
  Message VARCHAR(256) NOT NULL,
  PRIMARY KEY (id)
)
  DEFAULT CHARACTER SET utf8mb4
  ENGINE = InnoDB
;
